### ISSUE TITLE
Bug: id is undefined in the response when posting a quote

### ISSUE THREAD

**Issue by tahminahesari** [oanhgle/bangtan-api#3]
##  bugreport

Hi @oanhgle,

Thanks for making this project, I'm going to use it for a school assigment. I found a bug when posting a quote, the "id" in the response is undefined.  I added screenshot below.

![2022-01-24 13_41_44-Postman](https://user-images.githubusercontent.com/65297923/150785568-6cd221e0-d85b-47f4-9de1-cdccd346eb41.png)
 
Keep going nice work 💜

**Comment by oanhgle** [comment]
Thanks for reporting! Issue has been fixed in [d256791](https://github.com/oanhgle/bangtan-api/commit/d2567917b001f628118070d284744475a2095ea3)
